### ISSUE TITLE
Wrapping libcmark?

### ISSUE THREAD

**Issue by gjtorikian** [jgm/commonmarker#1]
Hi @jgm! I noticed this line in the README:

> It would be nice to have the gem build the library as a ruby extension, but I leave that for someone with more knowledge of ruby extensions to implement.

I have some decent experience doing this, and would actually prefer to consume the gem in that manner, so I don't mind making a PR to get this work going.

My question to you would be how you would prefer to keep the C project in sync with this wrapper? In the past, when wrapping C projects with Ruby, I've usually placed the C project as a submodule of the Ruby gem. When the C library is updated, you have to remember to go to the Ruby gem, update the submodule, and publish a new release (I usually do this in a single script). Does that approach make sense to you, or would you prefer something else?

**Comment by jgm** [comment]
+++ Garen Torikian [May 02 15 10:22 ]:

> Hi @jgm! I noticed this line in the README:
> 
> > It would be nice to have the gem build the library as a ruby extension, but I leave that for someone with more knowledge of ruby extensions to implement.
> 
> I have some decent experience doing this, and would actually prefer to consume the gem in that manner, so I don't mind making a PR to get this work going.
> 
> My question to you would be how you would prefer to keep the C project in sync with this wrapper? In the past, when wrapping C projects with Ruby, I've usually placed the C project as a submodule of the Ruby gem. When the C library is updated, you have to remember to go to the Ruby gem, update the submodule, and publish a new release (I usually do this in a single script). Does that approach make sense to you, or would you prefer something else?

Makes sense to me!
